import pg from 'pg';import {readFile} from 'node:fs/promises';import {fileURLToPath} from 'node:url';import path from 'node:path';import crypto from 'node:crypto';import {hashPin} from './auth.mjs';
const id=prefix=>`${prefix}_${crypto.randomUUID()}`;const now=()=>new Date().toISOString();
const memory={users:[],students:[],signals:[],attendance:[],interventions:[],recoveries:[],family_responses:[],outcomes:[],audit_events:[]};let pool=null;
const demoStudents=[{id:'stu_amina',name:'Amina Yusuf',class_name:'SS2',parent_user_id:'usr_parent',route:'Gwagwalada'},{id:'stu_daniel',name:'Daniel Obi',class_name:'JSS3',route:'Kubwa'},{id:'stu_zainab',name:'Zainab Musa',class_name:'SS1',route:'Gwagwalada'},{id:'stu_samuel',name:'Samuel Eze',class_name:'JSS2',route:'Karu'}];
async function demoUsers(){return[{id:'usr_admin',school_id:'LH-ADMIN',name:'Principal Adeyemi',role:'admin',pin_hash:await hashPin(process.env.DEMO_ADMIN_PIN||'2026')},{id:'usr_teacher',school_id:'LH-TEACHER',name:'Mrs Okafor',role:'teacher',pin_hash:await hashPin(process.env.DEMO_TEACHER_PIN||'2468')},{id:'usr_student',school_id:'LH-STUDENT',name:'Amina Yusuf',role:'student',linked_student_id:'stu_amina',pin_hash:await hashPin(process.env.DEMO_STUDENT_PIN||'1357')},{id:'usr_parent',school_id:'LH-PARENT',name:'Mrs Yusuf',role:'parent',linked_student_id:'stu_amina',phone:process.env.DEMO_PARENT_PHONE||'',pin_hash:await hashPin(process.env.DEMO_PARENT_PIN||'8642')},{id:'usr_safe',school_id:'LH-SAFE',name:'Safeguarding Lead',role:'safeguarding',pin_hash:await hashPin(process.env.DEMO_SAFEGUARD_PIN||'9753')}];}
export async function initStore(){if(process.env.DATABASE_URL){const local=/localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL);pool=new pg.Pool({connectionString:process.env.DATABASE_URL,ssl:local||process.env.DATABASE_SSL==='false'?false:{rejectUnauthorized:false}});const root=path.dirname(path.dirname(fileURLToPath(import.meta.url)));await pool.query(await readFile(path.join(root,'schema.sql'),'utf8'));const users=await demoUsers();for(const s of demoStudents)await pool.query('INSERT INTO students(id,name,class_name,parent_user_id,route) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO NOTHING',[s.id,s.name,s.class_name,s.parent_user_id||null,s.route]);for(const u of users)await pool.query('INSERT INTO users(id,school_id,name,role,pin_hash,linked_student_id,phone) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(school_id) DO NOTHING',[u.id,u.school_id,u.name,u.role,u.pin_hash,u.linked_student_id||null,u.phone||null]);console.log('PostgreSQL connected and schema ready');}else{memory.students=structuredClone(demoStudents);memory.users=await demoUsers();console.warn('DATABASE_URL missing: using temporary in-memory demo data');}}
const q=async(text,values=[])=>pool?(await pool.query(text,values)).rows:null;
export async function findUserBySchoolId(schoolId){if(pool)return(await q('SELECT * FROM users WHERE UPPER(school_id)=UPPER($1)',[schoolId]))[0];return memory.users.find(u=>u.school_id.toUpperCase()===String(schoolId).toUpperCase());}
export async function getStudent(studentId){if(pool)return(await q('SELECT * FROM students WHERE id=$1',[studentId]))[0];return memory.students.find(s=>s.id===studentId);}
export async function audit(actorId,action,entityType,entityId,metadata={}){const row={id:id('aud'),actor_id:actorId,action,entity_type:entityType,entity_id:entityId,metadata,created_at:now()};if(pool)await q('INSERT INTO audit_events(id,actor_id,action,entity_type,entity_id,metadata) VALUES($1,$2,$3,$4,$5,$6)',[row.id,actorId,action,entityType,entityId,JSON.stringify(metadata)]);else memory.audit_events.unshift(row);return row;}
export async function createSignal({studentId,category,note='',urgent=false}){const row={id:id('sig'),student_id:studentId,category,note,urgent:!!urgent,status:'new',visibility:['safety','health'].includes(category)?'safeguarding':'support',created_at:now()};if(pool)await q('INSERT INTO signals(id,student_id,category,note,urgent,status,visibility) VALUES($1,$2,$3,$4,$5,$6,$7)',[row.id,row.student_id,row.category,row.note,row.urgent,row.status,row.visibility]);else memory.signals.unshift(row);return row;}
export async function listSignals(user){let rows=pool?await q('SELECT s.*,st.name student_name,st.class_name,st.route FROM signals s JOIN students st ON st.id=s.student_id ORDER BY s.created_at DESC LIMIT 100'):memory.signals.map(s=>({...s,...(()=>{const st=memory.students.find(x=>x.id===s.student_id)||{};return{student_name:st.name,class_name:st.class_name,route:st.route}})()}));if(['student','parent'].includes(user.role))rows=rows.filter(r=>r.student_id===user.linkedStudentId);if(user.role==='teacher')rows=rows.filter(r=>r.visibility!=='safeguarding').map(r=>({...r,note:''}));if(user.role==='admin')rows=rows.map(r=>r.visibility==='safeguarding'?{...r,note:'Restricted safeguarding signal',category:'safeguarding'}:r);return rows;}
export async function saveAttendance({records,className,markedBy}){const date=new Date().toISOString().slice(0,10),saved=[];for(const r of records){const row={id:id('att'),student_id:r.studentId,state:r.state,class_name:className,lesson_date:date,marked_by:markedBy,created_at:now()};if(pool)await q('INSERT INTO attendance(id,student_id,class_name,state,lesson_date,marked_by) VALUES($1,$2,$3,$4,$5,$6)',[row.id,row.student_id,row.class_name,row.state,row.lesson_date,row.marked_by]);else memory.attendance.push(row);saved.push(row)}return saved;}
export async function createIntervention({studentId,signalId,title,ownerId,actions,followUpAt,createdBy}){const row={id:id('int'),student_id:studentId,signal_id:signalId||null,title,owner_id:ownerId||null,status:'assigned',actions,follow_up_at:followUpAt||null,created_by:createdBy,created_at:now(),updated_at:now()};if(pool)await q('INSERT INTO interventions(id,student_id,signal_id,title,owner_id,status,actions,follow_up_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[row.id,row.student_id,row.signal_id,row.title,row.owner_id,row.status,JSON.stringify(actions||[]),row.follow_up_at,row.created_by]);else memory.interventions.unshift(row);return row;}
export async function createRecovery({studentId,subject,topic,content,createdBy}){const row={id:id('rec'),student_id:studentId,subject,topic,content,status:'assigned',created_by:createdBy,created_at:now()};if(pool)await q('INSERT INTO recoveries(id,student_id,subject,topic,content,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[row.id,row.student_id,row.subject,row.topic,JSON.stringify(content),row.status,row.created_by]);else memory.recoveries.unshift(row);return row;}
export async function saveFamilyResponse({studentId,response,channel='web'}){const row={id:id('fam'),student_id:studentId,response,channel,created_at:now()};if(pool)await q('INSERT INTO family_responses(id,student_id,response,channel) VALUES($1,$2,$3,$4)',[row.id,row.student_id,row.response,row.channel]);else memory.family_responses.unshift(row);return row;}
export async function recordOutcome(data,userId){const row={id:id('out'),intervention_id:data.interventionId,attendance_improved:!!data.attendanceImproved,learning_recovered:!!data.learningRecovered,student_confirmed:!!data.studentConfirmed,note:data.note||'',recorded_by:userId,created_at:now()};if(pool)await q('INSERT INTO outcomes(id,intervention_id,attendance_improved,learning_recovered,student_confirmed,note,recorded_by) VALUES($1,$2,$3,$4,$5,$6,$7)',[row.id,row.intervention_id,row.attendance_improved,row.learning_recovered,row.student_confirmed,row.note,row.recorded_by]);else memory.outcomes.unshift(row);return row;}
export async function dashboard(user){const signals=await listSignals(user);let interventions=pool?await q('SELECT i.*,st.name student_name FROM interventions i JOIN students st ON st.id=i.student_id ORDER BY i.created_at DESC LIMIT 100'):memory.interventions;let recoveries=pool?await q('SELECT * FROM recoveries ORDER BY created_at DESC LIMIT 100'):memory.recoveries;if(['student','parent'].includes(user.role)){interventions=interventions.filter(x=>x.student_id===user.linkedStudentId);recoveries=recoveries.filter(x=>x.student_id===user.linkedStudentId)}const routeCounts={};signals.forEach(s=>{if(s.route)routeCounts[s.route]=(routeCounts[s.route]||0)+1});return{signals,interventions,recoveries,metrics:{openSignals:signals.filter(s=>s.status!=='resolved').length,activeInterventions:interventions.filter(i=>i.status!=='resolved').length,recoveriesAssigned:recoveries.length},routePatterns:Object.entries(routeCounts).map(([route,count])=>({route,count})).sort((a,b)=>b.count-a.count)};}
export async function getAudit(user){if(!['admin','safeguarding'].includes(user.role))return[];return pool?await q('SELECT * FROM audit_events ORDER BY created_at DESC LIMIT 100'):memory.audit_events.slice(0,100);}
